#!bin/bash

###### NAVIGATION #####

alias icloud='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/'

alias home='cd ~'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias dv='cd ~/Developer'
alias dot='cd ~/.dotfiles'

alias up='cd ..'
alias 2up='up && up'

alias g-n='cd ~/Developer/electron-gn/src'
alias el='cd ~/Developer/electron-gn/src/electron'
alias enode='cd ~/Developer/electron-gn/src/third_party/electron_node'
alias libuv='dv && cd libuv'
alias repros='dv && cd repros'

##### TERMINAL COMMANDS ######

alias _='sudo'
alias cls='clear'
alias a="code -a"
alias g='git'

alias r!='source ~/.zshrc'

alias lc='colorls'
alias stat='colorls --gs'
alias tree='colorls --group-directories-first --tree=2'

alias spotoff='sudo mdutil -a -i off'
alias spoton='sudo mdutil -a -i on'

alias c='tr -d '\n' | pbcopy'

# toggle VoiceOver
alias vo='sh ~/.dotfiles/config_files/vo.sh'

##### PROCESSES #####

alias serve='http-server -o'
alias sp='speed-test'

##### MISC ######

alias localip='ipconfig getifaddr en0'

##### NODE #####

# build Node.js
alias nc='./configure --ninja'

# build Node.js with clang
alias nb='ninja -C out/Release'

# lint Node.js
alias nl='make lint'

# run test suites
alias nt='make -j12 test'

##### LIBUV #####

# build libuv
alias lb='./gyp_uv.py -f make && make -C out'

# run test suites
alias lt='./out/Debug/run-tests'

##### AZURE #####

# start windows azure vm
alias az-start='az vm start -g codebytere-personal -n Codebytere-VM'

# stop windows azure vm
alias az-stop='az vm stop -g codebytere-personal -n Codebytere-VM'

##### MISC #####

alias logisim='java -jar /Applications/Logisim.app/Contents/Resources/Java/logisim.jar'
