#!bin/bash

############### NAVIGATION ###############

alias icloud='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/'

alias home='cd ~'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias dv='cd ~/Developer'
alias dot='cd ~/.dotfiles'

alias up='cd ..'
alias 2up='up && up'
alias 3up='2up && up'

########### TERMINAL COMMANDS ############

alias _='sudo'
alias cls='clear'
alias a="code -a"
alias g='git'

alias r!='source ~/.dotfiles/.zshrc'

alias spotoff='sudo mdutil -a -i off'
alias spoton='sudo mdutil -a -i on'

alias c='tr -d '\n' | pbcopy'

############### PROCESSES ###############

alias serve='http-server -o'
alias sp='speed-test'

alias lin-me='dv && cd vagrant && vagrant up linux'

############### MISC ###############

alias localip='ipconfig getifaddr en0'

#lock the screen
alias lksc='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'

# volume
alias stfu='osascript -e "set volume output muted true"'
alias uptop='osascript -e "set volume output volume 100"'
