#!bin/bash

############### NAVIGATION ###############

alias icloud='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/'
alias duke='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Duke/'
alias sen='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Duke/Senior/Fall'

alias home='cd ~'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias dv='cd ~/Developer'

alias e='dv && cd electron'
alias repros='dv && cd repros'

alias up='cd ..'
alias 2up='up && up'
alias 3up='2up && up'

########### TERMINAL COMMANDS ############

alias _='sudo'
alias cls='clear'
alias a="atom -a"

alias reload!='source ~/.dotfiles/.zshrc'

alias spotoff='sudo mdutil -a -i off'
alias spoton='sudo mdutil -a -i on'

alias c='tr -d '\n' | pbcopy'

############### WORK ###############

alias eb="~/Developer/electron/script/bootstrap.py -v"
alias ebd="~/Developer/electron/script/build.py -c D"
alias ebr="~/Developer/electron/script/build.py -c R"

alias erun="~/Developer/electron/out/D/Electron.app/Contents/MacOS/Electron"
alias ebrun="ebd && erun"
alias et="ebd && npm run test"
alias ecov="ebd && npm run coverage"

alias debug="lldb ~/Developer/electron/out/D/Electron.app"

############### PROCESSES ###############

alias serve="http-server -o"

alias lin-me="dv && cd vagrant && vagrant up linux"
alias win-me="dv && cd vagrant && vagrant up windows"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

############### MISC ###############

alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

alias localip="ipconfig getifaddr en0" #get IP address

#lock the screen
alias lksc="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# volume
alias stfu="osascript -e 'set volume output muted true'"
alias uptop="osascript -e 'set volume output volume 100'"

#recursively delete DS_Store files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
