#!bin/bash

############### NAVIGATION ###############

alias icloud='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/'
alias duke='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Duke/'
alias sen='cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Duke/Senior/Fall'

alias home='cd ~'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias dv='cd ~/Developer'
alias dot='cd ~/.dotfiles'

alias e='dv && cd @electron/electron'
alias enode='dv && cd @electron/node'
alias repros='dv && cd @electron/repros'
alias node='dv && cd @node/node'

alias up='cd ..'
alias 2up='up && up'
alias 3up='2up && up'

########### TERMINAL COMMANDS ############

alias _='sudo'
alias cls='clear'
alias a="atom -a"

alias reload!='source ~/.dotfiles/.zshrc'

alias spotoff='sudo mdutil -a -i off'
alias spoton='sudo mdutil -a -i on'

alias c='tr -d '\n' | pbcopy'

############### WORK ###############

alias work='cd ~/Developer/@codebytere/does-work'

alias eb='~/Developer/@electron/electron/script/bootstrap.py -d -v'
alias ebd='~/Developer/@electron/electron/script/build.py -c D'
alias ebr='~/Developer/@electron/electron/script/build.py -c R'
alias ebbd='eb && ebd'
alias ebbr='eb && ebr'

alias erun='~/Developer/@electron/electron/out/D/Electron.app/Contents/MacOS/Electron'
alias ebrun='ebd && erun'
alias et='ebd && npm run test'
alias ec='npm run clean && ebbd'

alias sap='script/patch.py -r src -p'
alias usap='script/patch.py -R -r src -p'

alias debug='lldb ~/Developer/@electron/electron/out/D/Electron.app'

alias sim='node_modules/.bin/probot simulate'

############### PROCESSES ###############

alias serve='http-server -o'
alias sp='speed-test'

alias lin-me='dv && cd vagrant && vagrant up linux'

############### MISC ###############

alias localip='ipconfig getifaddr en0' #get IP address

#lock the screen
alias lksc='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'

# volume
alias stfu='osascript -e "set volume output muted true"'
alias uptop='osascript -e "set volume output volume 100"'
