#!/bin/bash

function require_apm() {
  running "apm $1"
  if [[ $(apm list --local | grep $1 | head -1 | cut -d' ' -f1) != $1 ]];
    then
      action "apm install $1"
      apm install $1
  fi
  ok
}

# misc packages
require_apm atom-beautify
require_apm javascript-snippets
require_apm language-mips
require_apm advanced-open-file

# linter packages
require_apm linter
require_apm linter-erb
require_apm linter-eslint
require_apm linter-jsonlint
require_apm linter-chktex
require_apm linter-shellcheck
require_apm linter-pylint

require_apm build-python
require_apm merge-conflicts
require_apm pigments

# theme
require_apm pristine-ui

bot "atom packages installed successfully"
