#!/bin/bash

######### BREW PKGS ##########
running "installing python3"
brew install python

########## APPS ###########

running "installing apps with brew cask"

# https://www.electronjs.org/fiddle
brew install --cask electron-fiddle

# https://flexibits.com/fantastical
brew install --cask fantastical

# https://fig.io
brew install --cask fig

# https://iterm2.com
brew install --cask iterm2

# https://www.google.com/chrome
brew install --cask google-chrome

# https://notion.so
brew install --cask notion

# https://polymail.io
brew install --cask polymail

# https://slack.com
brew install --cask slack

# https://signal.org
brew install --cask signal

# https://spotify.com
brew install --cask spotify

# https://github.com/exelban/stats
brew install --cask stats

# https://code.visualstudio.com
brew install --cask visual-studio-code

# https://www.whatsapp.com
brew install --cask whatsapp

# https://1password.com
brew install --cask 1password

running "cleaning up cask files"
brew cask cleanup

bot "chosen brew packages installed successfully"
