#!/bin/bash

######### BREW PKGS ##########
running "installing python"
brew install python

running "installing zsh"
brew install zsh

brew install fontconfig

########## APPS ###########
running "installing brew cask"
brew tap caskroom/cask

#### DEVELOPMENT ####
brew cask install iterm2
brew cask install atom
brew cask install vlc
brew cask install spotify
brew cask install transmission
brew cask install slack
brew cask install nylas-n1
brew cask install goofy
brew cask install google-chrome
brew cask install dockertoolbox
brew cask install flux
brew cask install dropbox
brew cask install 1password

running "cleaning up cask files"
brew cask cleanup

bot "chosen brew and brew cask packages installed successfully"
