#!/bin/bash

function require_npm() {
  running "npm $*"
  npm list -g --depth 0 | grep $1@ > /dev/null
  if [[ $? != 0 ]]; then
    action "npm install -g $*"
    npm install -g $@
  fi
  ok
}

require_npm http-server
require_npm speed-test
require_npm pretty-error

bot "your chosen npm packages installed successfully"
