# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "linux", autostart: false do |linux|
    linux.vm.box = "fasmat/ubuntu1804-desktop"
    linux.vm.network "public_network"
    linux.vm.synced_folder "~/Developer", "/shared"

    linux.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = 8000
    end
  end

  config.vm.define "win", autostart: false do |win|
    win.vm.box = "Microsoft/EdgeOnWindows10"
    win.vm.network "public_network"
    win.vm.synced_folder "~/Developer", "/shared"

    win.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "60"]
      vb.gui = true
      vb.memory = 8000
    end
  end
end
